version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: youtube_sharing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd@123
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
